### PR TITLE
Updated README.md for PS1_SNe_Ia

### PR DESCRIPTION
**Pull request by benboyd97**
Fixed link to paper

### CODE REVIEW

**Comment by benboyd97** [comment]
not sure why this is failing because I pulled from main and just changed a README.md

**Comment by EiffL** [comment]
@benboyd97 can you update to the main branch, there has been an update of a library in dependencies that breaks things. I forced the previous vrsion, should work now if you update

**Review by EiffL — APPROVED** [review]
LGTM

**Comment by benboyd97** [comment]
thanks @EiffL!

**Pull request merged**
